name: Deploy Backend to Azure Container Apps

on:
  push:
    branches:
      - main

env:
  AZURE_CONTAINER_REGISTRY: ${{ vars.AZURE_CONTAINER_REGISTRY }}
  AZURE_RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
  CONTAINER_APP_NAME: ${{ vars.CONTAINER_APP_NAME }}
  CONTAINER_APP_ENVIRONMENT: ${{ vars.CONTAINER_APP_ENVIRONMENT }}
  IMAGE_NAME: 'openscg-server'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push Docker image using Azure CLI
      run: |
        az acr build --registry ${{ env.AZURE_CONTAINER_REGISTRY }} --image ${{ env.IMAGE_NAME }}:${{ github.sha }} --file server/Dockerfile ./server

    - name: Delete Existing Container App (to ensure clean state)
      run: |
        az containerapp delete --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --yes || echo "Container app not found, proceeding to create."

    - name: Create and Deploy to Azure Container Apps
      run: |
        az containerapp create \
          --name ${{ env.CONTAINER_APP_NAME }} \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --environment ${{ env.CONTAINER_APP_ENVIRONMENT }} \
          --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} \
          --registry-server ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io \
          --target-port 8000 \
          --ingress external \
          --query properties.configuration.ingress.fqdn
